# -*- coding: utf-8 -*-
"""Calling_BERT_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19DUjPAEBS1FZqczgoFU3TVwiEDT1pJAO
"""

# Commented out IPython magic to ensure Python compatibility.
import json
import requests
# %time
url="http://54.199.241.207:5000/get_sentiment"
review={'Review': 'this is a good movie'}
review =json.dumps(review)

x=requests.post(url,review)
print(x.text)

# Commented out IPython magic to ensure Python compatibility.
# %time
review={'Review': 'this movie makes me discomfortable'}
review =json.dumps(review)

x=requests.post(url,review)
print(x.text)

